### PR TITLE
installed nextjs for frontend

### PR DESCRIPTION
**Pull request by OLINYA-PAUL**
## installed nextjs for frontend
Next.js is a powerful React framework for building fast, scalable, and server-side-rendered web applications.

## Reasons why nextjs is a game changer!

- [ ] Server-side Rendering (SSR): Next.js offers built-in SSR, allowing pages to be rendered on the server and delivered to the 
client as fully rendered HTML. This improves SEO, performance, and enables faster initial page loads.
- [ ] Static Site Generation (SSG): With Next.js, you can pre-render entire pages at build time, resulting in static HTML files. This approach ensures incredible performance, as the server doesn't need to regenerate the page for each request.
- [ ] Automatic Code Splitting: Next.js automatically splits code into smaller chunks, loading only the required JavaScript for each page. This reduces initial bundle size and speeds up page loads.
- [ ] API Routes: Next.js provides a simple way to create serverless API endpoints directly within the application, streamlining the process of developing backend functionality.
- [ ] And much more.

If there is any additional information that is relevant

### CODE REVIEW

**Comment by OLINYA-PAUL** [comment]
Thanking you, am happy to work on your project for self improvement.

**Review by freedompraise — COMMENTED** [review]
Hello, Paul
Can you move the installed files into the frontend folder?

It's not okay for the next.js installation to be in the home folder

**Comment by Paul-Rust** [comment]
Yes bro, though I installed the nextjs application purposely on the home directory , I will  move it in the front end folder.
But it gonna cause some issues on the react files installed on the front end while starting react.

May be I will get read of all the react files,  fix nextjs install folder into the front end directory making nextjs permanent application for the frontend.

**Comment by freedompraise** [comment]
> Yes bro, though I installed the nextjs application purposely on the home directory , I will move it in the front end folder. But it gonna cause some issues on the react files installed on the front end while starting react.
> 
> May be I will get read of all the react files, fix nextjs install folder into the front end directory making nextjs permanent application for the frontend.

alright. 
Resolve it before I merge

**Comment by freedompraise** [comment]
> > Yes bro, though I installed the nextjs application purposely on the home directory , I will move it in the front end folder. But it gonna cause some issues on the react files installed on the front end while starting react.
> > May be I will get read of all the react files, fix nextjs install folder into the front end directory making nextjs permanent application for the frontend.
> 
> alright. Resolve it before I merge

or rather, make a new pr for it @OLINYA-PAUL

**Pull request merged**
